### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-carmen-tm#1]
Good job @carmen-tm  !!!

Here you have some tips to improve the exercise:

- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto
- [x] Fix the language and the title of the page
- [x] We need an h1 tag
- [x] Move the font CSS before your main CSS
- [x] Remove commented CSS rules
- [x] Main title should be vertically centered (should we use Flex to achieve this?)
- [x] Something is generating an unwanted vertical scroll, let's fix it.
- [x] Avoid capital on HTML texts, and `br` tag, we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Finish the main title styles: words should jump and the typography is bolder
- [x] Menu items and logo should be clickable
- [x] Class selectors are free, let's use them instead tag selectors 
- [x] Fix the header to the viewport
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background-color...
- [x] Main section should fit 100% of the browser's height
- [x] Instead of adding extra space at the bottom of the header, you can make the menu links taller, that would make the header be tall enough and also would make the link easier to touch on mobile devices ;)
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs

Let me know if you have any doubts ;)

Go for it!!

**Comment by carmen-tm** [comment]
Hi @nasivuela !
This is done finally :)
Thank you for the feedback, it was really helpful!

**Comment by nasivuela** [comment]
Ey @carmen-tm, I have unchecked a couple of points that can be improved.

The meta title of the page shouldn't be about yourself or the evaluation, probably something like 'Adalab Digital' would do the trick.

In the main title on tablet version, the word 'Diversidad' is slightly moved to the right. It looks like the box is too narrow and is pushing it.

**Comment by carmen-tm** [comment]
@nasivuela 
Done! sorry for that, I didn't realize the container had that problem, you were totally right. Now it works well, and I have changed the web title as well. Thanks!!

**Comment by nasivuela** [comment]
No sorry needed ;) Those were just little details to make it purrfect, and you got it!!!
Super @carmen-tm !!

![](https://media.giphy.com/media/VgmDj1F00Njag/giphy.gif)
